# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:8080/calc
Content-Type: application/json

{
  "token": -1446678487,
  "operation": {
    "var1": 2,
    "var2": 2.0,
    "operationType": "mult"
  }
}

###

GET http://localhost:8080/history
Content-Type: application/json

{
  "token": -1446678487
}

###

PUT http://localhost:8080/user/reg
Content-Type: application/json

{
  "nickname": "Test",
  "login": "test@test.com",
  "password": "test"
}

###

POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "login": "test@test.com",
  "password": "test"
}

###

DELETE http://localhost:8080/user/logout
Content-Type: application/json

{
  "token": -1446678487
}

###